apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - httproute.yml
images:
  - name: tournament-website
    digest: sha256:97c7af5ae7ec8f1d1894f426e993e3d416cdee3b887826eee6c5bc9dc8dd9404
    newName: ghcr.io/accsaber/tournament-2
    newTag: latest
configMapGenerator:
  - name: acc-tournament-config
    envs:
      - config.env
secretGenerator:
  - name: acc-tournament-secret
    envs:
      - prod.env
