apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yml
  - deployment.yml
  - service.yml
  - httproute.yml
images:
  - name: tournament-website
    newName: ghcr.io/accsaber/tournament-2
configMapGenerator:
  - name: acc-tournament-config
    envs:
      - config.env
secretGenerator:
  - name: acc-tournament-secret
    options:
      disableNameSuffixHash: true
    envs:
      - prod.env
commonLabels:
  app: tournament-website
  