apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - httproute.yml
images:
  - name: tournament-website
    digest: sha256:2c48a06f344c2c04f1daaa67ff03eba960ce5c03615fbc122fdfae810171260c
    newName: ghcr.io/accsaber/tournament-2
    newTag: latest
configMapGenerator:
  - name: acc-tournament-config
    envs:
      - config.env
secretGenerator:
  - name: acc-tournament-secret
    envs:
      - prod.env
