apiVersion: v1
kind: ServiceAccount
metadata:
  name: tournament-sa
imagePullSecrets:
  - name: ghcr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tournament-list-endpoints
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tournament-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tournament-list-endpoints
subjects:
  - kind: ServiceAccount
    name: tournament-sa
    namespace: default
